version: "2"
services:
  ushahidi:
    build:
      context: .
      dockerfile: Dockerfile.apache
    command: run
    volumes:
      - .tars:/tars
    links:
      - mysql
    ports:
      - 80:80
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ushahidi
      MYSQL_USER: ushahidi
      MYSQL_PASSWORD: ushahidi
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ushahidi
      MYSQL_USER: ushahidi
      MYSQL_PASSWORD: ushahidi
